### PR TITLE
Add Custom Comment to Head of Manifest

### PR DESCRIPTION
**Pull request by shake10861**
Added an option to append a custom comment to the top of the manifest file. This is particularly useful if users want to trigger the manifest to change only when they update the app version in their package.json file.

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
:+1: for this PR.

**Comment by fagnervalente** [comment]
Nice feature, but isn`t in documentation.

**Comment by andykono** [comment]
Sorry, why it not merged?

**Comment by gunta** [comment]
Thank you!

**Pull request merged**
